# Generated by Django 5.2.6 on 2025-10-23 05:14

import medical_data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonfile',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='jsonfile',
            name='file',
            field=models.FileField(upload_to=medical_data.models.medical_json_file_path, validators=[medical_data.models.validate_json_extension], verbose_name='JSON файл'),
        ),
    ]
